### PR TITLE
Updating TokenDict with length

### PR DESCRIPTION
**Pull request by fletcher512**
Added __len__ to TokenDict. This dispatches to 'len(self.dict_)'. Updated some whitespace in attrgraph.py.

### CODE REVIEW

**Comment by ethanrowe** [comment]
I would be happier about merging this if you had a unit test or two demonstrating that len() now works.
How would you feel about doing that?

**Comment by fletcher512** [comment]
Okay, I can add one.

**Comment by ethanrowe** [comment]
Sauce awesome.

**Comment by ethanrowe** [comment]
I shall merge your changes with great delight.

**Comment by fletcher512** [comment]
thanks

**Pull request merged**
